#!/usr/bin/env bash
# =============================================================================
# LabWiFiMon Server Setup Script
# Prepares directories, generates secrets, and starts the Docker stack.
# Run from the pi-server/ directory: bash setup.sh
# =============================================================================
set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GRN='\033[0;32m'
YLW='\033[1;33m'
BLU='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLU}[INFO]${NC}  $*"; }
ok()    { echo -e "${GRN}[ OK ]${NC}  $*"; }
warn()  { echo -e "${YLW}[WARN]${NC}  $*"; }
die()   { echo -e "${RED}[FAIL]${NC}  $*" >&2; exit 1; }

echo ""
echo -e "${GRN}╔══════════════════════════════════════╗${NC}"
echo -e "${GRN}║   LabWiFiMon — Server Setup          ║${NC}"
echo -e "${GRN}╚══════════════════════════════════════╝${NC}"
echo ""

# ── Sanity checks ─────────────────────────────────────────────────────────────
info "Checking prerequisites..."

command -v docker &>/dev/null || die "Docker is not installed. See https://docs.docker.com/engine/install/"

if docker compose version &>/dev/null 2>&1; then
    COMPOSE="docker compose"
elif command -v docker-compose &>/dev/null; then
    COMPOSE="docker-compose"
else
    die "Docker Compose is not installed. Update Docker Desktop or install the compose plugin."
fi
ok "Docker + Compose found  (using: $COMPOSE)"

command -v openssl &>/dev/null || die "openssl is required to generate tokens."

# ── Ensure we're in the right directory ───────────────────────────────────────
[[ -f docker-compose.yml ]] || die "Run this script from the pi-server/ directory."

# ── Create host directories needed for volume mounts ─────────────────────────
info "Creating host directories..."
mkdir -p \
    mosquitto/{config,data,log} \
    telegraf \
    grafana/{provisioning/{datasources,dashboards},dashboards} \
    influxdb
ok "Directories ready."

# ── Generate .env ─────────────────────────────────────────────────────────────
if [[ -f .env ]] && grep -qv "CHANGE_ME" .env 2>/dev/null; then
    warn ".env already exists with real values — skipping generation."
    warn "Delete .env and re-run setup.sh to regenerate secrets."
else
    info "Generating secrets..."

    INFLUXDB_TOKEN=$(openssl rand -base64 48 | tr -d '\n/+=' | head -c 64)
    INFLUXDB_ADMIN_PW=$(openssl rand -base64 12 | tr -d '\n/+=')
    GF_ADMIN_PW=$(openssl rand -base64 12 | tr -d '\n/+=')

    cat > .env <<EOF
# LabWiFiMon — generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT commit this file to version control.

INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
INFLUXDB_ORG=labwifimon
INFLUXDB_BUCKET=wifi_metrics
INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PW}
GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PW}
EOF
    ok ".env written with randomly generated secrets."
fi

# Load .env for printing URLs later
# shellcheck disable=SC1091
source .env

# ── Pull/build images ─────────────────────────────────────────────────────────
info "Pulling images and building throughput server..."
$COMPOSE pull --ignore-buildable 2>&1 | grep -E "Pulled|Already exists|pulling|latest" || true
$COMPOSE build throughput-server

# ── Start the stack ───────────────────────────────────────────────────────────
info "Starting services..."
$COMPOSE up -d

echo ""
info "Waiting for services to become healthy (up to 60 s)..."
DEADLINE=$((SECONDS + 60))
SERVICES=(influxdb mosquitto grafana)
while [[ $SECONDS -lt $DEADLINE ]]; do
    ALL_HEALTHY=true
    for svc in "${SERVICES[@]}"; do
        STATUS=$($COMPOSE ps --format json "$svc" 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('Health','unknown'))" 2>/dev/null || echo "unknown")
        [[ "$STATUS" == "healthy" ]] || ALL_HEALTHY=false
    done
    $ALL_HEALTHY && break
    echo -n "."
    sleep 3
done
echo ""

# ── Print access info ─────────────────────────────────────────────────────────
# Determine the Pi's primary LAN IP
LAN_IP=$(ip route get 8.8.8.8 2>/dev/null | awk '/src/ {for(i=1;i<=NF;i++) if($i=="src") print $(i+1)}' | head -1)
LAN_IP=${LAN_IP:-localhost}

# Read Grafana password from .env (may have been pre-existing)
GF_PW=$(grep "^GF_SECURITY_ADMIN_PASSWORD=" .env | cut -d= -f2-)

echo ""
echo -e "${GRN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GRN}║   LabWiFiMon is running!                                 ║${NC}"
echo -e "${GRN}╠══════════════════════════════════════════════════════════╣${NC}"
echo -e "${GRN}║${NC}  Grafana dashboards  →  ${BLU}http://${LAN_IP}:3000${NC}"
echo -e "${GRN}║${NC}    Login: admin / ${YLW}${GF_PW}${NC}"
echo -e "${GRN}║${NC}"
echo -e "${GRN}║${NC}  InfluxDB UI         →  ${BLU}http://${LAN_IP}:8086${NC}"
echo -e "${GRN}║${NC}  MQTT broker         →  ${LAN_IP}:1883 (no auth)"
echo -e "${GRN}║${NC}  Throughput payload  →  ${BLU}http://${LAN_IP}:8080/test_payload.bin${NC}"
echo -e "${GRN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${YLW}Point your ESP32 probes at MQTT broker: ${LAN_IP}:1883${NC}"
echo -e "${YLW}Publish to: labwifimon/<probe_id>/metrics|scan|status${NC}"
echo ""
echo "To view logs:    $COMPOSE logs -f"
echo "To stop stack:   $COMPOSE down"
echo "To wipe data:    $COMPOSE down -v"
echo ""
